# 通用配置，动态指定默认为开发dev环境
spring:
  profiles:
    active: dev
## 微信配置
wx:
  appid: wx67618f9dbb31145d
  secret: cc95806e95b3973dfb04eaf229d84d43
  url: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&grant_type=authorization_code&js_code=

