# 生产环境配置
# http服务端口
server:
  port: 8092
# DATASOURCE
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.69.104:3306/redflower2?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: root
    password: whalexhh
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
      #update:加载Hibernate自动更新数据库结构，会保留数据
      #create-drop:加载Hibernate时创建，退出时删除
      #create:每次加载Hibernate，重新创建数据库表结构
    show-sql: true
  devtools:
    restart:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.web: warn
    com.weizhi.redflower2: warn
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
  file: redflower2.prod.log